services:
  - type: web
    name: ueno-leilao-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
