services:
  - type: web
    name: ueno-leilao-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///ueno.db
    autoDeploy: true

